// Generated from rules/schema/*.schema.json by npm run rules:generate.
// Do not edit this file directly.

export type UtcTimestamp = string;
export type Identifier = string;
export type Kind = "TARIFF" | "LEGAL" | "HOLIDAY";
export type IsoDate = string;
export type VersionIdentifier = string;

/**
 * Signed, immutable catalog of rule packages available to an app installation.
 */
export interface PflegeShiftRuleManifest {
  schemaVersion: 1;
  generation: number;
  channel: "PREVIEW" | "PRODUCTION";
  publishedAt: UtcTimestamp;
  rollbackOfGeneration: null | number;
  /**
   * @minItems 1
   */
  tracks: [Track, ...Track[]];
  /**
   * @minItems 1
   */
  packages: [PackageDescriptor, ...PackageDescriptor[]];
  signing: Signing;
}
export interface Track {
  packageId: Identifier;
  kind: Kind;
  coverageFrom: IsoDate;
  coverageTo: null | IsoDate;
  coverage: "COMPLETE" | "PARTIAL";
}
export interface PackageDescriptor {
  packageId: Identifier;
  versionId: VersionIdentifier;
  kind: Kind;
  engineContractVersion: 1 | 2 | 3 | 4 | 5 | 6 | 7;
  validFrom: IsoDate;
  validTo: null | IsoDate;
  path: string;
  sha256: string;
  sizeBytes: number;
}
export interface Signing {
  algorithm: "ED25519";
  canonicalization: "RFC8785";
  keyId: Identifier;
  /**
   * Unpadded base64url Ed25519 signature over the UTF-8 RFC 8785 canonical JSON of the complete manifest with only this signature property omitted.
   */
  signature: string;
}

/**
 * A typed, reviewable package of tariff, legal, or public-holiday rules. Executable code is not allowed.
 */
export type PflegeShiftRulePackage = RuleTariffPackage | RuleLegalPackage | RuleHolidayPackage;
export type RuleTariffPackage = RulePackageBase & {
  engineContractVersion?: 1 | 2 | 3;
  kind: "TARIFF";
  rules: RuleTariffRules;
};
export type RuleIdentifier = string;
export type RuleVersionIdentifier = string;
export type RuleIsoDate = string;
export type RuleNullableDate = null | RuleIsoDate;
export type RuleFederalState =
  | "BW"
  | "BY"
  | "BE"
  | "BB"
  | "HB"
  | "HH"
  | "HE"
  | "MV"
  | "NI"
  | "NW"
  | "RP"
  | "SL"
  | "SN"
  | "ST"
  | "SH"
  | "TH";
export type RuleReview = {
  status: "LEGACY_EMBEDDED" | "DRAFT" | "REVIEWED" | "PUBLISHED";
  /**
   * Stable non-personal reviewer identifier. The solo project owner may self-review; a legal name, separate role, or second reviewer is not required.
   */
  reviewedBy: null | string;
  /**
   * UTC timestamp recorded when the documented owner review is completed.
   */
  reviewedAt: null | RuleUtcTimestamp;
  /**
   * Exact 40-character Git commit containing the rule content that was reviewed.
   */
  gitCommit: null | string;
} & RuleReview1;
export type RuleUtcTimestamp = string;
export type RuleReview1 =
  | {
      status?: "LEGACY_EMBEDDED" | "DRAFT";
      reviewedBy?: null;
      reviewedAt?: null;
      gitCommit?: null;
    }
  | {
      status?: "REVIEWED" | "PUBLISHED";
      reviewedBy?: string;
      reviewedAt?: RuleUtcTimestamp;
      gitCommit?: string;
    };
/**
 * @minItems 1
 */
export type RuleSourceIds = [RuleIdentifier, ...RuleIdentifier[]];
export type RuleNullableIdentifier = null | RuleIdentifier;
export type RuleLegalPackage = RulePackageBase & {
  engineContractVersion?: 1 | 3 | 4 | 5 | 6;
  kind: "LEGAL";
  rules: RuleLegalRules;
};
export type RuleHolidayPackage = RulePackageBase & {
  engineContractVersion?: 1 | 2 | 7;
  kind: "HOLIDAY";
  rules: RuleHolidayRules;
};

export interface RulePackageBase {
  schemaVersion: 1;
  engineContractVersion: 1 | 2 | 3 | 4 | 5 | 6 | 7;
  packageId: RuleIdentifier;
  versionId: RuleVersionIdentifier;
  kind: "TARIFF" | "LEGAL" | "HOLIDAY";
  label: string;
  status: "LEGACY_EMBEDDED" | "DRAFT" | "REVIEWED" | "PUBLISHED";
  validFrom: RuleIsoDate;
  validTo: RuleNullableDate;
  jurisdiction: RuleJurisdiction;
  /**
   * @minItems 1
   */
  sources: [RuleSource, ...RuleSource[]];
  review: RuleReview;
  rounding: RuleRounding;
  rules: unknown;
}
export interface RuleJurisdiction {
  country: "DE";
  federalStates: null | [RuleFederalState, ...RuleFederalState[]];
}
export interface RuleSource {
  id: RuleIdentifier;
  title: string;
  url: string;
  documentDate: RuleIsoDate;
  section: string;
  sha256: string;
}
export interface RuleRounding {
  moneyScale: 2;
  mode: "HALF_UP";
  stage: "PER_LINE" | "AFTER_SUM";
}
export interface RuleTariffRules {
  selector:
    | {
        agreementId: RuleIdentifier;
        specialPartId: RuleIdentifier;
        payTableId: RuleIdentifier;
      }
    | {
        agreementId: RuleIdentifier;
        /**
         * @minItems 1
         */
        specialPartIds: [RuleIdentifier, ...RuleIdentifier[]];
        payTableId: RuleIdentifier;
      };
  /**
   * @minItems 1
   */
  payTables: [RulePayTable, ...RulePayTable[]];
  overtimeBaseRule?: RuleOvertimeBaseRule;
  /**
   * @minItems 1
   */
  weeklyWorkingTimeRules?: [RuleWeeklyWorkingTimeRule, ...RuleWeeklyWorkingTimeRule[]];
  hourlyCalculation?: RuleHourlyCalculation;
  premiumRules: RulePremiumRule[];
  allowanceRules: RuleAllowanceRule[];
  combinationRules: RuleCombinationRule[];
  workPatternRules: RuleWorkPatternRule[];
  workPatternPolicy: RuleWorkPatternPolicy;
}
export interface RulePayTable {
  id: RuleIdentifier;
  /**
   * @minItems 1
   */
  entries: [RulePayTableEntry, ...RulePayTableEntry[]];
  sourceIds: RuleSourceIds;
}
export interface RulePayTableEntry {
  groupId: RuleIdentifier;
  stepId: RuleIdentifier;
  monthlyCents: number;
  hourlyCents?: number;
}
export interface RuleOvertimeBaseRule {
  maximumStepId: RuleIdentifier;
  sourceIds: RuleSourceIds;
}
export interface RuleWeeklyWorkingTimeRule {
  id: RuleIdentifier;
  /**
   * @minItems 1
   */
  sectors: ["BT_K" | "BT_B", ...("BT_K" | "BT_B")[]];
  /**
   * @minItems 1
   */
  tariffRegions: ["KAV_BW" | "OTHER", ...("KAV_BW" | "OTHER")[]];
  fullTimeWeeklyMinutes: number;
  sourceIds: RuleSourceIds;
}
export interface RuleHourlyCalculation {
  monthlyFactorThousandths: 4348;
  rounding: "HALF_UP";
  sourceIds: RuleSourceIds;
}
export interface RulePremiumRule {
  id: RuleIdentifier;
  label: string;
  premiumType:
    | "NIGHT"
    | "SUNDAY"
    | "HOLIDAY_WITH_TIME_OFF"
    | "HOLIDAY_WITHOUT_TIME_OFF"
    | "SATURDAY"
    | "PRE_HOLIDAY"
    | "OVERTIME";
  percentageBasisPoints: number;
  rateBasis: "INDIVIDUAL_HOURLY" | "TABLE_STEP";
  referenceStepId: RuleNullableIdentifier;
  timeWindow: null | RuleTimeWindow;
  conditions: RuleConditions;
  sourceIds: RuleSourceIds;
}
export interface RuleTimeWindow {
  startMinute: number;
  endMinute: number;
}
export interface RuleConditions {
  requiresShiftTypes: RuleIdentifier[];
  excludesShiftTypes: RuleIdentifier[];
  payGroups: null | [RuleIdentifier, ...RuleIdentifier[]];
  sectors: null | ["BT_K" | "BT_B", ...("BT_K" | "BT_B")[]];
  federalStates: null | [RuleFederalState, ...RuleFederalState[]];
  tariffRegions?: null | ["KAV_BW" | "OTHER", ...("KAV_BW" | "OTHER")[]];
  holidayPremiumModes:
    null | ["WITH_TIME_OFF" | "WITHOUT_TIME_OFF", ...("WITH_TIME_OFF" | "WITHOUT_TIME_OFF")[]];
  allowanceStatuses:
    | null
    | [
        "SHIFT_MONTHLY" | "SHIFT_HOURLY" | "ALTERNATING_MONTHLY" | "ALTERNATING_HOURLY",
        ...("SHIFT_MONTHLY" | "SHIFT_HOURLY" | "ALTERNATING_MONTHLY" | "ALTERNATING_HOURLY")[],
      ];
  monthDays: null | [string, ...string[]];
}
export interface RuleAllowanceRule {
  id: RuleIdentifier;
  allowanceType: RuleIdentifier;
  amountKind: "FIXED_MONTHLY" | "FIXED_HOURLY";
  amountCents: number;
  prorateByPartTime: boolean;
  validFrom: RuleIsoDate;
  validTo: RuleNullableDate;
  conditions: RuleConditions;
  sourceIds: RuleSourceIds;
}
export interface RuleCombinationRule {
  id: RuleIdentifier;
  /**
   * @minItems 2
   */
  memberRuleIds: [RuleIdentifier, RuleIdentifier, ...RuleIdentifier[]];
  mode: "STACK" | "EXCLUSIVE_HIGHEST" | "PRIORITY";
  priorityRuleIds: RuleIdentifier[];
  sourceIds: RuleSourceIds;
}
export interface RuleWorkPatternRule {
  id: RuleIdentifier;
  metric: "CONSECUTIVE_NIGHT_SHIFTS" | "WORKED_MINUTES" | "NIGHT_MINUTES" | "CONSECUTIVE_WORK_DAYS";
  comparator: "GT" | "GTE" | "EQ";
  threshold: number;
  windowDays: null | number;
  sourceIds: RuleSourceIds;
}
export interface RuleWorkPatternPolicy {
  nightWindow: RuleTimeWindow;
  nightQualificationMinutes: number;
  recurringNightShiftCount: number;
  recurringWindowMonths: number;
  regularChangeCount: number;
  shiftWorkMinimumShifts: number;
  shiftWorkMinimumWindows: number;
  alternatingMinimumShifts: number;
  alternatingMinimumWindows: number;
  assessmentLookbackMonths: number;
  shiftWindowBoundaries: {
    nightEndMinute: number;
    earlyEndMinute: number;
    dayEndMinute: number;
    nightStartMinute: number;
  };
  sourceIds: RuleSourceIds;
}
export interface RuleLegalRules {
  workingTime: {
    standardDailyMinutes: number;
    maxDailyMinutes: number;
    nightAverageMinutes: number;
    workWeekLastDay: number;
    absenceWorkdaysPerWeek: number;
    standardAverage?: {
      calendarMonths: number;
      weeks: number;
      assessmentMode: "FORWARD_FROM_EXTENDED_WORKDAY";
      neutralAbsenceTypes: ["VACATION", "SICK"];
    };
    grossPlanningWarningMinutes: number;
    sourceIds: RuleSourceIds;
  };
  breaks: {
    minimumSegmentMinutes: number;
    /**
     * @minItems 1
     */
    tiers: [RuleBreakTier, ...RuleBreakTier[]];
    sourceIds: RuleSourceIds;
  };
  nightWork: {
    startMinute: number;
    endMinute: number;
    qualification: {
      comparator: "GT" | "GTE" | "EQ";
      thresholdMinutes: number;
    };
    workerQualification?: {
      regularRotatingNightWorkRequiresConfirmation: true;
      annualNightWorkDaysThreshold: number;
    };
    averageWindowDays: null | number;
    sourceIds: RuleSourceIds;
  };
  restPeriod: {
    defaultMinutes: number;
    deviations: RuleRestDeviation[];
    sourceIds: RuleSourceIds;
  };
  sundayHolidayRest?: RuleSundayHolidayRest;
  planning: {
    consecutiveWorkDaysWarning: number;
    consecutiveNightShiftsWarning: number;
    consecutiveWeekendGapDays: number;
    lateEarlyDayGap: number;
    sourceIds: RuleSourceIds;
  };
}
export interface RuleBreakTier {
  overMinutes: number;
  requiredMinutes: number;
}
export interface RuleRestDeviation {
  id: RuleIdentifier;
  /**
   * @minItems 1
   */
  sectorIds: [RuleIdentifier, ...RuleIdentifier[]];
  minimumMinutes: number;
  compensationMinutes: number;
  compensationWithinDays: number;
  compensationWithinCalendarMonths?: number;
  sourceIds: RuleSourceIds;
}
export interface RuleSundayHolidayRest {
  /**
   * @minItems 1
   */
  eligibleSectorIds: [RuleIdentifier, ...RuleIdentifier[]];
  minimumFreeSundaysPerCalendarYear: number;
  sundayCompensationPeriodDays: number;
  weekdayHolidayCompensationPeriodDays: number;
  replacementDayMinutes: 1440;
  connectedRestMinutes: number;
  connectionExceptionMode: "TECHNICAL_OR_OPERATIONAL_REVIEW";
  evidenceShiftType: "FREE";
  matchingMode: "ONE_TO_ONE_EARLIEST_DEADLINE";
  sourceIds: RuleSourceIds;
}
export interface RuleHolidayRules {
  /**
   * @minItems 1
   */
  holidays: [RuleHoliday, ...RuleHoliday[]];
}
export interface RuleHoliday {
  id: RuleIdentifier;
  name: string;
  scope: "NATIONWIDE" | "STATEWIDE" | "REGIONAL";
  federalStates: null | [RuleFederalState, ...RuleFederalState[]];
  regionIds?: null | [RuleIdentifier, ...RuleIdentifier[]];
  validFrom: RuleIsoDate;
  validTo: RuleNullableDate;
  calculation:
    | {
        type: "FIXED_DATE";
        month: number;
        day: number;
      }
    | {
        type: "EASTER_OFFSET";
        offsetDays: number;
      }
    | {
        type: "REPENTANCE_DAY";
      }
    | {
        type: "SPECIFIC_DATE";
        date: RuleIsoDate;
      };
  sourceIds: RuleSourceIds;
}

export type PublicationUtcTimestamp = string;
export type PublicationIdentifier = string;

/**
 * Administrative input for producing one signed, immutable rule-catalog generation.
 */
export interface PflegeShiftRuleCatalogPublicationRequest {
  schemaVersion: 1;
  generation: number;
  channel: "PREVIEW" | "PRODUCTION";
  publishedAt: PublicationUtcTimestamp;
  rollbackOfGeneration: null | number;
  /**
   * @minItems 1
   */
  packageSources: [string, ...string[]];
  signing: PublicationSigning;
}
export interface PublicationSigning {
  algorithm: "ED25519";
  canonicalization: "RFC8785";
  keyId: PublicationIdentifier;
}

export type RuleManifest = PflegeShiftRuleManifest;
export type RulePackage = PflegeShiftRulePackage;
export type RuleCatalogPublicationRequest = PflegeShiftRuleCatalogPublicationRequest;
