// Generated from rules/schema/*.schema.json by npm run rules:generate.
// Do not edit this file directly.

export type UtcTimestamp = string;
export type Identifier = string;
export type Kind = "TARIFF" | "LEGAL" | "HOLIDAY";
export type IsoDate = string;
export type VersionIdentifier = string;

/**
 * Signed, immutable catalog of rule packages available to an app installation.
 */
export interface PflegeShiftRuleManifest {
  schemaVersion: 1;
  generation: number;
  channel: "PREVIEW" | "PRODUCTION";
  publishedAt: UtcTimestamp;
  rollbackOfGeneration: null | number;
  /**
   * @minItems 1
   */
  tracks: [Track, ...Track[]];
  /**
   * @minItems 1
   */
  packages: [PackageDescriptor, ...PackageDescriptor[]];
  signing: Signing;
}
export interface Track {
  packageId: Identifier;
  kind: Kind;
  coverageFrom: IsoDate;
  coverageTo: null | IsoDate;
  coverage: "COMPLETE" | "PARTIAL";
}
export interface PackageDescriptor {
  packageId: Identifier;
  versionId: VersionIdentifier;
  kind: Kind;
  engineContractVersion: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 11 | 14;
  validFrom: IsoDate;
  validTo: null | IsoDate;
  path: string;
  sha256: string;
  sizeBytes: number;
}
export interface Signing {
  algorithm: "ED25519";
  canonicalization: "RFC8785";
  keyId: Identifier;
  /**
   * Unpadded base64url Ed25519 signature over the UTF-8 RFC 8785 canonical JSON of the complete manifest with only this signature property omitted.
   */
  signature: string;
}

/**
 * A typed, reviewable package of tariff, legal, or public-holiday rules. Executable code is not allowed.
 */
export type PflegeShiftRulePackage = RuleTariffPackage | RuleLegalPackage | RuleHolidayPackage;
export type RuleTariffPackage = RulePackageBase & {
  engineContractVersion?: 1 | 2 | 3 | 11 | 14;
  kind: "TARIFF";
  rules: RuleTariffRules;
};
export type RuleIdentifier = string;
export type RuleVersionIdentifier = string;
export type RuleIsoDate = string;
export type RuleNullableDate = null | RuleIsoDate;
export type RuleFederalState =
  | "BW"
  | "BY"
  | "BE"
  | "BB"
  | "HB"
  | "HH"
  | "HE"
  | "MV"
  | "NI"
  | "NW"
  | "RP"
  | "SL"
  | "SN"
  | "ST"
  | "SH"
  | "TH";
export type RuleReview = {
  status: "LEGACY_EMBEDDED" | "DRAFT" | "REVIEWED" | "PUBLISHED";
  /**
   * Stable non-personal reviewer identifier. The solo project owner may self-review; a legal name, separate role, or second reviewer is not required.
   */
  reviewedBy: null | string;
  /**
   * UTC timestamp recorded when the documented owner review is completed.
   */
  reviewedAt: null | RuleUtcTimestamp;
  /**
   * Exact 40-character Git commit containing the rule content that was reviewed.
   */
  gitCommit: null | string;
} & RuleReview1;
export type RuleUtcTimestamp = string;
export type RuleReview1 =
  | {
      status?: "LEGACY_EMBEDDED" | "DRAFT";
      reviewedBy?: null;
      reviewedAt?: null;
      gitCommit?: null;
    }
  | {
      status?: "REVIEWED" | "PUBLISHED";
      reviewedBy?: string;
      reviewedAt?: RuleUtcTimestamp;
      gitCommit?: string;
    };
export type RuleSelectionIdentifier = string;
/**
 * @minItems 1
 */
export type RuleSourceIds = [RuleIdentifier, ...RuleIdentifier[]];
export type RuleCapabilityStatus = "SUPPORTED" | "UNSUPPORTED" | "NOT_APPLICABLE";
export type RuleNullableIdentifier = null | RuleIdentifier;
export type RuleLegalPackage = RulePackageBase & {
  engineContractVersion?: 1 | 3 | 4 | 5 | 6;
  kind: "LEGAL";
  rules: RuleLegalRules;
};
export type RuleHolidayPackage = RulePackageBase & {
  engineContractVersion?: 1 | 2 | 7;
  kind: "HOLIDAY";
  rules: RuleHolidayRules;
};

export interface RulePackageBase {
  schemaVersion: 1;
  engineContractVersion: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 11 | 14;
  packageId: RuleIdentifier;
  versionId: RuleVersionIdentifier;
  kind: "TARIFF" | "LEGAL" | "HOLIDAY";
  label: string;
  status: "LEGACY_EMBEDDED" | "DRAFT" | "REVIEWED" | "PUBLISHED";
  validFrom: RuleIsoDate;
  validTo: RuleNullableDate;
  jurisdiction: RuleJurisdiction;
  /**
   * @minItems 1
   */
  sources: [RuleSource, ...RuleSource[]];
  review: RuleReview;
  rounding: RuleRounding;
  rules: unknown;
}
export interface RuleJurisdiction {
  country: "DE";
  federalStates: null | [RuleFederalState, ...RuleFederalState[]];
}
export interface RuleSource {
  id: RuleIdentifier;
  title: string;
  url: string;
  documentDate: RuleIsoDate;
  section: string;
  sha256: string;
}
export interface RuleRounding {
  moneyScale: 2;
  mode: "HALF_UP";
  stage: "PER_LINE" | "AFTER_SUM";
}
export interface RuleTariffRules {
  selection?: RuleTariffSelection;
  /**
   * @minItems 1
   * @maxItems 200
   */
  annualPaymentRules?: [RuleAnnualPaymentRule, ...RuleAnnualPaymentRule[]];
  selector:
    | {
        agreementId: RuleIdentifier;
        specialPartId: RuleIdentifier;
        payTableId: RuleIdentifier;
      }
    | {
        agreementId: RuleIdentifier;
        /**
         * @minItems 1
         */
        specialPartIds: [RuleIdentifier, ...RuleIdentifier[]];
        payTableId: RuleIdentifier;
      };
  /**
   * @minItems 1
   */
  payTables: [RulePayTable, ...RulePayTable[]];
  overtimeBaseRule?: RuleOvertimeBaseRule;
  /**
   * @minItems 1
   */
  weeklyWorkingTimeRules?: [RuleWeeklyWorkingTimeRule, ...RuleWeeklyWorkingTimeRule[]];
  /**
   * @minItems 1
   * @maxItems 100
   */
  employmentWorkingTimeRules?: [RuleEmploymentWorkingTimeRule, ...RuleEmploymentWorkingTimeRule[]];
  /**
   * @minItems 1
   * @maxItems 200
   */
  caritasCareAllowanceRates?: [RuleCaritasCareAllowanceRate, ...RuleCaritasCareAllowanceRate[]];
  hourlyCalculation?: RuleHourlyCalculation;
  premiumRules: RulePremiumRule[];
  allowanceRules: RuleAllowanceRule[];
  combinationRules: RuleCombinationRule[];
  workPatternRules: RuleWorkPatternRule[];
  workPatternPolicy: RuleWorkPatternPolicy;
}
export interface RuleTariffSelection {
  familyId: RuleIdentifier;
  engineId: RuleIdentifier;
  employmentKind: "EMPLOYEE" | "APPRENTICE";
  /**
   * @minItems 1
   * @maxItems 100
   */
  variants: [
    {
      id: RuleSelectionIdentifier;
      label: string;
      specialPartId: RuleIdentifier;
      sourceIds: RuleSourceIds;
      /**
       * @minItems 1
       * @maxItems 100
       */
      regions: [
        {
          id: RuleSelectionIdentifier;
          label: string;
          payTableId?: RuleIdentifier;
          sourceIds: RuleSourceIds;
        },
        ...{
          id: RuleSelectionIdentifier;
          label: string;
          payTableId?: RuleIdentifier;
          sourceIds: RuleSourceIds;
        }[],
      ];
    },
    ...{
      id: RuleSelectionIdentifier;
      label: string;
      specialPartId: RuleIdentifier;
      sourceIds: RuleSourceIds;
      /**
       * @minItems 1
       * @maxItems 100
       */
      regions: [
        {
          id: RuleSelectionIdentifier;
          label: string;
          payTableId?: RuleIdentifier;
          sourceIds: RuleSourceIds;
        },
        ...{
          id: RuleSelectionIdentifier;
          label: string;
          payTableId?: RuleIdentifier;
          sourceIds: RuleSourceIds;
        }[],
      ];
    }[],
  ];
  capabilities: {
    basePay: RuleCapabilityStatus;
    timePremiums: RuleCapabilityStatus;
    allowances: RuleCapabilityStatus;
    overtime: RuleCapabilityStatus;
    annualPayment: RuleCapabilityStatus;
  };
}
/**
 * Contracts 11 (VKA) and 12 (TV-L): declarative annual payment terms. Personal confirmations are not public catalog data. Policies identify bundled algorithms, never remote code.
 */
export interface RuleAnnualPaymentRule {
  id: RuleIdentifier;
  variantId: RuleSelectionIdentifier;
  /**
   * @minItems 1
   * @maxItems 100
   */
  regionIds: [RuleSelectionIdentifier, ...RuleSelectionIdentifier[]];
  /**
   * @minItems 1
   * @maxItems 100
   */
  payGroups: [RuleIdentifier, ...RuleIdentifier[]];
  firstEntitlementYear: number;
  lastEntitlementYear: number;
  rateBasisPoints: number;
  /**
   * Three reference months, or November only for TVA-L Pflege §16; semantic validation enforces the policy.
   *
   * @minItems 1
   * @maxItems 3
   */
  referenceMonths: [number] | [number, number] | [number, number, number];
  lateEntryAfterMonth: number;
  basisPolicy: "TVOED_VKA_20" | "TVAOED_PFLEGE_14" | "TVL_20" | "TVAL_PFLEGE_16";
  eligibilityPolicy:
    | "EMPLOYED_DECEMBER_1"
    | "BT_K_EARLY_EXIT"
    | "TRAINING_OR_DIRECT_TAKEOVER_DECEMBER_1"
    | "TVAL_TRAINING_OR_DIRECT_TAKEOVER_DECEMBER_1"
    | "TVL_DECEMBER_1_OR_LEGACY_ATZ";
  reductionPolicy: "TVOED_VKA_20" | "TVAOED_PFLEGE_14" | "TVL_20" | "TVAL_PFLEGE_16";
  earlyExitBasis: "NONE" | "LAST_FULL_MONTH_TABLE_AND_FIXED_ALLOWANCES" | "LAST_THREE_MONTHS_TVL";
  payoutMonth: number;
  sourceIds: RuleSourceIds;
}
export interface RulePayTable {
  id: RuleIdentifier;
  /**
   * @minItems 1
   */
  entries: [RulePayTableEntry, ...RulePayTableEntry[]];
  sourceIds: RuleSourceIds;
}
export interface RulePayTableEntry {
  groupId: RuleIdentifier;
  stepId: RuleIdentifier;
  monthlyCents: number;
  hourlyCents?: number;
}
export interface RuleOvertimeBaseRule {
  maximumStepId: RuleIdentifier;
  sourceIds: RuleSourceIds;
}
export interface RuleWeeklyWorkingTimeRule {
  id: RuleIdentifier;
  /**
   * @minItems 1
   */
  sectors: ["BT_K" | "BT_B", ...("BT_K" | "BT_B")[]];
  /**
   * @minItems 1
   */
  tariffRegions: ["KAV_BW" | "OTHER", ...("KAV_BW" | "OTHER")[]];
  fullTimeWeeklyMinutes: number;
  sourceIds: RuleSourceIds;
}
/**
 * Dated full-time basis for one explicit variant and tariff territory.
 */
export interface RuleEmploymentWorkingTimeRule {
  id: RuleIdentifier;
  variantId: RuleSelectionIdentifier;
  regionId: RuleSelectionIdentifier;
  validFrom: RuleIsoDate;
  validTo: RuleNullableDate;
  fullTimeWeeklyMinutes: number;
  sourceIds: RuleSourceIds;
}
/**
 * Contract 14: sourced monthly care allowance rate for a provision, annex, territory and date range. A rate is not an individual entitlement or an activated calculation.
 */
export interface RuleCaritasCareAllowanceRate {
  id: RuleIdentifier;
  provisionId: "SECTION_12_3" | "SECTION_12_4";
  variantId: RuleSelectionIdentifier;
  regionId: RuleSelectionIdentifier;
  validFrom: RuleIsoDate;
  validTo: RuleIsoDate;
  monthlyCents: number;
  sourceIds: RuleSourceIds;
}
export interface RuleHourlyCalculation {
  monthlyFactorThousandths: 4348;
  rounding: "HALF_UP";
  sourceIds: RuleSourceIds;
}
export interface RulePremiumRule {
  id: RuleIdentifier;
  label: string;
  premiumType:
    | "NIGHT"
    | "SUNDAY"
    | "HOLIDAY_WITH_TIME_OFF"
    | "HOLIDAY_WITHOUT_TIME_OFF"
    | "SATURDAY"
    | "PRE_HOLIDAY"
    | "OVERTIME";
  percentageBasisPoints: number;
  rateBasis: "INDIVIDUAL_HOURLY" | "TABLE_STEP";
  referenceStepId: RuleNullableIdentifier;
  timeWindow: null | RuleTimeWindow;
  conditions: RuleConditions;
  sourceIds: RuleSourceIds;
}
export interface RuleTimeWindow {
  startMinute: number;
  endMinute: number;
}
export interface RuleConditions {
  requiresShiftTypes: RuleIdentifier[];
  excludesShiftTypes: RuleIdentifier[];
  payGroups: null | [RuleIdentifier, ...RuleIdentifier[]];
  sectors: null | ["BT_K" | "BT_B", ...("BT_K" | "BT_B")[]];
  federalStates: null | [RuleFederalState, ...RuleFederalState[]];
  tariffRegions?: null | ["KAV_BW" | "OTHER", ...("KAV_BW" | "OTHER")[]];
  holidayPremiumModes:
    null | ["WITH_TIME_OFF" | "WITHOUT_TIME_OFF", ...("WITH_TIME_OFF" | "WITHOUT_TIME_OFF")[]];
  allowanceStatuses:
    | null
    | [
        "SHIFT_MONTHLY" | "SHIFT_HOURLY" | "ALTERNATING_MONTHLY" | "ALTERNATING_HOURLY",
        ...("SHIFT_MONTHLY" | "SHIFT_HOURLY" | "ALTERNATING_MONTHLY" | "ALTERNATING_HOURLY")[],
      ];
  monthDays: null | [string, ...string[]];
}
export interface RuleAllowanceRule {
  id: RuleIdentifier;
  allowanceType: RuleIdentifier;
  amountKind: "FIXED_MONTHLY" | "FIXED_HOURLY";
  amountCents: number;
  prorateByPartTime: boolean;
  validFrom: RuleIsoDate;
  validTo: RuleNullableDate;
  conditions: RuleConditions;
  sourceIds: RuleSourceIds;
}
export interface RuleCombinationRule {
  id: RuleIdentifier;
  /**
   * @minItems 2
   */
  memberRuleIds: [RuleIdentifier, RuleIdentifier, ...RuleIdentifier[]];
  mode: "STACK" | "EXCLUSIVE_HIGHEST" | "PRIORITY";
  priorityRuleIds: RuleIdentifier[];
  sourceIds: RuleSourceIds;
}
export interface RuleWorkPatternRule {
  id: RuleIdentifier;
  metric: "CONSECUTIVE_NIGHT_SHIFTS" | "WORKED_MINUTES" | "NIGHT_MINUTES" | "CONSECUTIVE_WORK_DAYS";
  comparator: "GT" | "GTE" | "EQ";
  threshold: number;
  windowDays: null | number;
  sourceIds: RuleSourceIds;
}
export interface RuleWorkPatternPolicy {
  nightWindow: RuleTimeWindow;
  nightQualificationMinutes: number;
  recurringNightShiftCount: number;
  recurringWindowMonths: number;
  regularChangeCount: number;
  shiftWorkMinimumShifts: number;
  shiftWorkMinimumWindows: number;
  alternatingMinimumShifts: number;
  alternatingMinimumWindows: number;
  assessmentLookbackMonths: number;
  shiftWindowBoundaries: {
    nightEndMinute: number;
    earlyEndMinute: number;
    dayEndMinute: number;
    nightStartMinute: number;
  };
  sourceIds: RuleSourceIds;
}
export interface RuleLegalRules {
  workingTime: {
    standardDailyMinutes: number;
    maxDailyMinutes: number;
    nightAverageMinutes: number;
    workWeekLastDay: number;
    absenceWorkdaysPerWeek: number;
    standardAverage?: {
      calendarMonths: number;
      weeks: number;
      assessmentMode: "FORWARD_FROM_EXTENDED_WORKDAY";
      neutralAbsenceTypes: ["VACATION", "SICK"];
    };
    grossPlanningWarningMinutes: number;
    sourceIds: RuleSourceIds;
  };
  breaks: {
    minimumSegmentMinutes: number;
    /**
     * @minItems 1
     */
    tiers: [RuleBreakTier, ...RuleBreakTier[]];
    sourceIds: RuleSourceIds;
  };
  nightWork: {
    startMinute: number;
    endMinute: number;
    qualification: {
      comparator: "GT" | "GTE" | "EQ";
      thresholdMinutes: number;
    };
    workerQualification?: {
      regularRotatingNightWorkRequiresConfirmation: true;
      annualNightWorkDaysThreshold: number;
    };
    averageWindowDays: null | number;
    sourceIds: RuleSourceIds;
  };
  restPeriod: {
    defaultMinutes: number;
    deviations: RuleRestDeviation[];
    sourceIds: RuleSourceIds;
  };
  sundayHolidayRest?: RuleSundayHolidayRest;
  planning: {
    consecutiveWorkDaysWarning: number;
    consecutiveNightShiftsWarning: number;
    consecutiveWeekendGapDays: number;
    lateEarlyDayGap: number;
    sourceIds: RuleSourceIds;
  };
}
export interface RuleBreakTier {
  overMinutes: number;
  requiredMinutes: number;
}
export interface RuleRestDeviation {
  id: RuleIdentifier;
  /**
   * @minItems 1
   */
  sectorIds: [RuleIdentifier, ...RuleIdentifier[]];
  minimumMinutes: number;
  compensationMinutes: number;
  compensationWithinDays: number;
  compensationWithinCalendarMonths?: number;
  sourceIds: RuleSourceIds;
}
export interface RuleSundayHolidayRest {
  /**
   * @minItems 1
   */
  eligibleSectorIds: [RuleIdentifier, ...RuleIdentifier[]];
  minimumFreeSundaysPerCalendarYear: number;
  sundayCompensationPeriodDays: number;
  weekdayHolidayCompensationPeriodDays: number;
  replacementDayMinutes: 1440;
  connectedRestMinutes: number;
  connectionExceptionMode: "TECHNICAL_OR_OPERATIONAL_REVIEW";
  evidenceShiftType: "FREE";
  matchingMode: "ONE_TO_ONE_EARLIEST_DEADLINE";
  sourceIds: RuleSourceIds;
}
export interface RuleHolidayRules {
  /**
   * @minItems 1
   */
  holidays: [RuleHoliday, ...RuleHoliday[]];
}
export interface RuleHoliday {
  id: RuleIdentifier;
  name: string;
  scope: "NATIONWIDE" | "STATEWIDE" | "REGIONAL";
  federalStates: null | [RuleFederalState, ...RuleFederalState[]];
  regionIds?: null | [RuleIdentifier, ...RuleIdentifier[]];
  validFrom: RuleIsoDate;
  validTo: RuleNullableDate;
  calculation:
    | {
        type: "FIXED_DATE";
        month: number;
        day: number;
      }
    | {
        type: "EASTER_OFFSET";
        offsetDays: number;
      }
    | {
        type: "REPENTANCE_DAY";
      }
    | {
        type: "SPECIFIC_DATE";
        date: RuleIsoDate;
      };
  sourceIds: RuleSourceIds;
}

export type PublicationUtcTimestamp = string;
export type PublicationIdentifier = string;

/**
 * Administrative input for producing one signed, immutable rule-catalog generation.
 */
export interface PflegeShiftRuleCatalogPublicationRequest {
  schemaVersion: 1;
  generation: number;
  channel: "PREVIEW" | "PRODUCTION";
  publishedAt: PublicationUtcTimestamp;
  rollbackOfGeneration: null | number;
  /**
   * @minItems 1
   */
  packageSources: [string, ...string[]];
  signing: PublicationSigning;
}
export interface PublicationSigning {
  algorithm: "ED25519";
  canonicalization: "RFC8785";
  keyId: PublicationIdentifier;
}

/**
 * Public, non-secret configuration candidate for a strictly isolated Production rule-catalog channel.
 */
export interface PflegeShiftProductionRuleCatalogChannelConfig {
  schemaVersion: 1;
  channel: "PRODUCTION";
  status: "DISABLED" | "CANDIDATE";
  infrastructure: {
    isolationMode: "DEDICATED_SUPABASE_PROJECT";
    supabaseProjectUrl: string | null;
    region: "eu-central-1";
    bucketName: "rule-catalog-production";
    objectRoot: "production";
    deliverySecretEnvironmentName: "SUPABASE_PRODUCTION_SECRET_KEY";
    storagePolicy: {
      publicRead: true;
      administrativeWriteOnly: true;
      allowedMimeTypes: ["application/json"];
      maximumObjectBytes: 524288;
    };
  };
  trust: {
    algorithm: "ED25519";
    canonicalization: "RFC8785";
    /**
     * @maxItems 8
     */
    trustedPublicKeys:
      | []
      | [
          {
            keyId: string;
            publicKeyBase64Url: string;
          },
        ]
      | [
          {
            keyId: string;
            publicKeyBase64Url: string;
          },
          {
            keyId: string;
            publicKeyBase64Url: string;
          },
        ]
      | [
          {
            keyId: string;
            publicKeyBase64Url: string;
          },
          {
            keyId: string;
            publicKeyBase64Url: string;
          },
          {
            keyId: string;
            publicKeyBase64Url: string;
          },
        ]
      | [
          {
            keyId: string;
            publicKeyBase64Url: string;
          },
          {
            keyId: string;
            publicKeyBase64Url: string;
          },
          {
            keyId: string;
            publicKeyBase64Url: string;
          },
          {
            keyId: string;
            publicKeyBase64Url: string;
          },
        ]
      | [
          {
            keyId: string;
            publicKeyBase64Url: string;
          },
          {
            keyId: string;
            publicKeyBase64Url: string;
          },
          {
            keyId: string;
            publicKeyBase64Url: string;
          },
          {
            keyId: string;
            publicKeyBase64Url: string;
          },
          {
            keyId: string;
            publicKeyBase64Url: string;
          },
        ]
      | [
          {
            keyId: string;
            publicKeyBase64Url: string;
          },
          {
            keyId: string;
            publicKeyBase64Url: string;
          },
          {
            keyId: string;
            publicKeyBase64Url: string;
          },
          {
            keyId: string;
            publicKeyBase64Url: string;
          },
          {
            keyId: string;
            publicKeyBase64Url: string;
          },
          {
            keyId: string;
            publicKeyBase64Url: string;
          },
        ]
      | [
          {
            keyId: string;
            publicKeyBase64Url: string;
          },
          {
            keyId: string;
            publicKeyBase64Url: string;
          },
          {
            keyId: string;
            publicKeyBase64Url: string;
          },
          {
            keyId: string;
            publicKeyBase64Url: string;
          },
          {
            keyId: string;
            publicKeyBase64Url: string;
          },
          {
            keyId: string;
            publicKeyBase64Url: string;
          },
          {
            keyId: string;
            publicKeyBase64Url: string;
          },
        ]
      | [
          {
            keyId: string;
            publicKeyBase64Url: string;
          },
          {
            keyId: string;
            publicKeyBase64Url: string;
          },
          {
            keyId: string;
            publicKeyBase64Url: string;
          },
          {
            keyId: string;
            publicKeyBase64Url: string;
          },
          {
            keyId: string;
            publicKeyBase64Url: string;
          },
          {
            keyId: string;
            publicKeyBase64Url: string;
          },
          {
            keyId: string;
            publicKeyBase64Url: string;
          },
          {
            keyId: string;
            publicKeyBase64Url: string;
          },
        ];
  };
  remote: {
    publicBaseUrl: string | null;
    checkIntervalMilliseconds: 86400000;
    failureRetryMilliseconds: 3600000;
  };
}

export type RuleManifest = PflegeShiftRuleManifest;
export type RulePackage = PflegeShiftRulePackage;
export type RuleCatalogPublicationRequest = PflegeShiftRuleCatalogPublicationRequest;
export type ProductionRuleCatalogChannelConfig = PflegeShiftProductionRuleCatalogChannelConfig;
